# Generated by Django 3.2.4 on 2023-02-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='preview_link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
